INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('3084/1_2004');
INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('2084/2_2004');
INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('4084/3_2004');

INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('Физика');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('Математика');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('Программирование');

INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Георгий', 'Голиков', 'Дмитриевич', '1', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Ярослав', 'Пылаев', 'Сергеевич', '2', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Филипп', 'Трофимов', 'Олегович', '3', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('Борис', 'Попов', 'Петрович', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('Надежда', 'Солева', 'Юрьевна', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('Алексей', 'Мартынов', 'Валерьевич', 'T');

INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('1', '1', '1', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('2', '2', '2', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('3', '3', '3', '5');