INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('3084/1_2005');
INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('2084/2_2005');
INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('4084/3_2006');

INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('������');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('����������');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('����������������');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('���');

INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('�������', '�������', '����������', '601', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('�������', '������', '���������', '602', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('������', '��������', '��������', '3', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('�����', '�����', '��������', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('�������', '������', '�������', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('�������', '��������', '����������', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('�������', '���������', '���������', '601', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('�������', '������', '���������', '601', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('�����', '���������', '����������', '601', 'S');

INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('75', '14', '23', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('76', '11', '24', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('77', '12', '25', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('80', '11', '24', '4');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('75', '12', '25', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('78', '14', '23', '5');