INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('3084/1_2005');
INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('2084/2_2005');
INSERT INTO "C##MY_USER"."GROUPS" (NAME) VALUES ('4084/3_2006');

INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('Физика');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('Математика');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('Программирование');
INSERT INTO "C##MY_USER"."SUBJECTS" (NAME) VALUES ('ООП');

INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Георгий', 'Голиков', 'Дмитриевич', '1', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Ярослав', 'Пылаев', 'Сергеевич', '2', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Филипп', 'Трофимов', 'Олегович', '3', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('Борис', 'Попов', 'Петрович', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('Надежда', 'Солева', 'Юрьевна', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, TYPE) VALUES ('Алексей', 'Мартынов', 'Валерьевич', 'T');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Дмитрий', 'Неупокоев', 'Андреевич', '1', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Валерия', 'Лукина', 'Александр', '1', 'S');
INSERT INTO "C##MY_USER"."PEOPLE" (FIRST_NAME, LAST_NAME, FATHER_NAME, GROUP_ID, TYPE) VALUES ('Алина', 'Муллагали', 'Шамильевна', '1', 'S');

INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('20', '9', '23', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('21', '10', '24', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('22', '11', '25', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('26', '10', '24', '4');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('20', '11', '25', '5');
INSERT INTO "C##MY_USER"."MARKS" (STUDENT_ID, SUBJECT_ID, TEACHER_ID, VALUE) VALUES ('28', '9', '23', '5');