/*
    Создание таблиц и добавление первичных ключей
*/

-- groups
--DROP TABLE groups;
CREATE TABLE groups (
    id NUMBER GENERATED BY DEFAULT as IDENTITY(START with 1 INCREMENT by 1 NOCACHE),
    name VARCHAR2(50) NOT NULL
);

ALTER TABLE groups
ADD CONSTRAINT groups_pk PRIMARY KEY (id);

-- people
--DROP TABLE people;
CREATE TABLE people (
    id NUMBER GENERATED BY DEFAULT as IDENTITY(START with 1 INCREMENT by 1 NOCACHE),
    first_name VARCHAR2(20) NOT NULL,
    last_name VARCHAR2(20) NOT NULL,
    father_name VARCHAR2(20),
    group_id NUMBER,
    type CHAR(1)
);

ALTER TABLE people
ADD CONSTRAINT people_pk PRIMARY KEY (id);

-- marks
--DROP TABLE marks;
CREATE TABLE marks (
    id NUMBER GENERATED BY DEFAULT as IDENTITY(START with 1 INCREMENT by 1 NOCACHE),
    student_id NUMBER NOT NULL,
    subject_id NUMBER NOT NULL,
    teacher_id NUMBER NOT NULL,
    value NUMBER NOT NULL
);

ALTER TABLE marks
ADD CONSTRAINT marks_pk PRIMARY KEY (id);

-- subjects
--DROP TABLE subjects;
CREATE TABLE subjects (
    id NUMBER GENERATED BY DEFAULT as IDENTITY(START with 1 INCREMENT by 1 NOCACHE),
    name VARCHAR2(50) NOT NULL
);

ALTER TABLE subjects
ADD CONSTRAINT subjects_pk PRIMARY KEY (id);


/*
    Создание связей между таблицами
*/

-- people - groups
ALTER TABLE people
ADD CONSTRAINT fk_people_groups
  FOREIGN KEY (group_id)
  REFERENCES groups(id);
  
-- marks - subjects
ALTER TABLE marks
ADD CONSTRAINT fk_marks_subjects
  FOREIGN KEY (subject_id)
  REFERENCES subjects(id);
  
-- marks - students
ALTER TABLE marks
ADD CONSTRAINT fk_marks_people1
  FOREIGN KEY (student_id)
  REFERENCES people(id);
  
-- marks - teachers
ALTER TABLE marks
ADD CONSTRAINT fk_marks_people2
  FOREIGN KEY (teacher_id)
  REFERENCES people(id);